"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { firebase as supabase, type Session } from "../../lib/firebase";

type Transfer={id:string;organization_id:string;operation_date:string;voter_id:string;voter_dni:string;voter_name:string;pickup_address:string;voter_phone?:string|null;destination_name:string;destination_address?:string|null;driver_name?:string|null;vehicle_plate?:string|null;status:"pendiente"|"buscada"|"en_destino"|"regresada";driver_user_id:string;mobilizer_user_id?:string|null;status_updated_at?:string|null};
const nextCopy:Record<Transfer["status"],string>={pendiente:"CONFIRMAR QUE SUBIÓ",buscada:"LA DEJÉ EN LA ESCUELA",en_destino:"LA LLEVÉ DE REGRESO",regresada:"TRASLADO FINALIZADO"};
const statusCopy:Record<Transfer["status"],string>={pendiente:"Pendiente",buscada:"En camino a votar",en_destino:"En la escuela",regresada:"Traslado finalizado"};

function getPosition(){return new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));}
function todayKey(){return new Date().toLocaleDateString("en-CA",{timeZone:"America/Argentina/Buenos_Aires"});}

export default function Movilidad(){
  const [session,setSession]=useState<Session|null>(null),[items,setItems]=useState<Transfer[]>([]),[active,setActive]=useState<Transfer|null>(null),[dni,setDni]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[ready,setReady]=useState(false);
  async function load(userId:string){
    const day=todayKey();
    const [driver,mobilizer]=await Promise.all([supabase.from("mobility_transfers").select("*").eq("driver_user_id",userId).eq("operation_date",day),supabase.from("mobility_transfers").select("*").eq("mobilizer_user_id",userId).eq("operation_date",day)]);
    const map=new Map<string,Transfer>();[...(driver.data??[]),...(mobilizer.data??[])].forEach(item=>map.set(String((item as Transfer).id),item as Transfer));
    const ordered=[...map.values()].sort((a,b)=>["pendiente","buscada","en_destino","regresada"].indexOf(a.status)-["pendiente","buscada","en_destino","regresada"].indexOf(b.status));setItems(ordered);setReady(true);
  }
  useEffect(()=>{void supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)void load(data.session.user.id);else setReady(true);});const sub=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);if(next)void load(next.user.id);else{setItems([]);setReady(true);}});return()=>sub.data.subscription.unsubscribe();},[]);
  const counts=useMemo(()=>items.reduce((acc,item)=>({...acc,[item.status]:acc[item.status]+1}),{pendiente:0,buscada:0,en_destino:0,regresada:0}),[items]);
  async function submit(event:FormEvent){event.preventDefault();if(!active||!session)return;setBusy(true);setMessage("");try{if(active.status==="pendiente"&&dni.replace(/\D/g,"").length<6)throw new Error("Ingresá el DNI completo antes de confirmar.");if(!navigator.geolocation)throw new Error("Este teléfono no permite compartir ubicación.");setMessage("Tomando ubicación…");const position=await getPosition();const result=await supabase.mobility.updateTransfer({id:active.id,dni,latitude:position.coords.latitude,longitude:position.coords.longitude});if(result.error)throw result.error;if(navigator.vibrate)navigator.vibrate([70,35,100]);setMessage("✓ Registro guardado correctamente");setDni("");await load(session.user.id);window.setTimeout(()=>{setActive(null);setMessage("");},900);}catch(cause){setMessage(cause instanceof Error?cause.message:"No se pudo guardar. Probá nuevamente.");}finally{setBusy(false);}}
  if(!ready)return <main className="mobility-shell"><div className="mobility-loading">Preparando operativo…</div></main>;
  if(!session)return <main className="mobility-shell"><section className="mobility-empty"><b>Operativo de movilidad</b><h1>Ingresá desde la app</h1><p>Usá tu usuario y contraseña asignados. Tu sesión queda guardada en este teléfono.</p><a href="/">Abrir acceso</a></section></main>;
  if(active)return <main className="mobility-shell"><header className="mobility-top"><button onClick={()=>{setActive(null);setDni("");setMessage("");}}>← Volver</button><span>TRASLADO EN CURSO</span></header><section className="mobility-detail"><span className={`mobility-status ${active.status}`}>{statusCopy[active.status]}</span><h1>{active.voter_name}</h1><p className="mobility-address">⌖ {active.pickup_address}</p>{active.voter_phone&&<a className="mobility-call" href={`tel:${active.voter_phone}`}>Llamar · {active.voter_phone}</a>}<div className="mobility-destination"><small>DESTINO ELECTORAL</small><b>{active.destination_name}</b><span>{active.destination_address||"Dirección a confirmar"}</span></div><form onSubmit={submit}>{active.status==="pendiente"&&<label className="mobility-dni">Confirmá el DNI completo<input value={dni} onChange={event=>setDni(event.target.value.replace(/\D/g,""))} inputMode="numeric" autoFocus placeholder="Escribí el DNI" maxLength={10}/></label>}<p className="mobility-location">⌖ Al confirmar se registrará tu ubicación.</p>{message&&<p className={message.startsWith("✓")?"mobility-success":"mobility-message"}>{message}</p>}<button className={`mobility-action ${active.status}`} disabled={busy||active.status==="regresada"}>{busy?"REGISTRANDO…":nextCopy[active.status]}</button></form></section></main>;
  return <main className="mobility-shell"><header className="mobility-hero"><div><span>OPERATIVO ELECTORAL · HOY</span><h1>Mi movilidad</h1><p>Estos son tus traslados asignados para hoy.</p></div><button onClick={()=>void supabase.auth.signOut()}>Salir</button></header><section className="mobility-summary"><b>{items.length}</b><span>traslados asignados</span><i>{counts.pendiente} pendientes</i></section><main className="mobility-list">{items.length===0?<div className="mobility-empty"><h2>Sin traslados para hoy</h2><p>Tu operador todavía no te asignó una hoja de ruta. Si ya la cargó, cerrá y abrí esta pantalla.</p></div>:items.map(item=><button className={`mobility-card ${item.status}`} key={item.id} onClick={()=>setActive(item)}><span className={`mobility-status ${item.status}`}>{statusCopy[item.status]}</span><strong>{item.voter_name}</strong><small>{item.pickup_address}</small><em>{item.destination_name}</em><i>→</i></button>)}</main></main>;
}
