"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { firebase as supabase } from "../../lib/firebase";

type Status="pendiente"|"buscada"|"en_destino"|"regresada";
type Stop={transfer_id:string;dni:string;full_name:string;pickup_address:string;voter_phone?:string|null;destination_name:string;destination_address?:string|null;status:Status;status_updated_at:string;last_latitude?:number|null;last_longitude?:number|null};
type Route={id:string;driver_name:string;vehicle_plate:string;operation_date:string;expires_at_ms:number;stops:Stop[]};
const nextCopy:Record<Status,string>={pendiente:"CONFIRMAR QUE SUBIÓ",buscada:"LA DEJÉ EN LA ESCUELA",en_destino:"LA LLEVÉ DE REGRESO",regresada:"TRASLADO FINALIZADO"};
const statusCopy:Record<Status,string>={pendiente:"Pendiente",buscada:"En camino a votar",en_destino:"En la escuela",regresada:"Traslado finalizado"};
function getPosition(){return new Promise<GeolocationPosition>((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000,maximumAge:0}));}

export default function Movilidad(){
  const [code,setCode]=useState(""),[route,setRoute]=useState<Route|null>(null),[active,setActive]=useState<Stop|null>(null),[dni,setDni]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[ready,setReady]=useState(false);
  async function openRoute(value:string){const clean=value.trim().toUpperCase();if(!clean)return;setBusy(true);setMessage("");try{const result=await supabase.from("mobility_driver_routes").select("*").eq("id",clean).maybeSingle();const item=result.data as Route|null;if(result.error||!item||item.expires_at_ms<Date.now())throw new Error("Código no válido o jornada vencida. Pedíselo nuevamente a tu movilizador.");setRoute(item);setCode(clean);localStorage.setItem("movilidad_route_code",clean);}catch(cause){setMessage(cause instanceof Error?cause.message:"No se pudo abrir la jornada.");}finally{setBusy(false);setReady(true);}}
  useEffect(()=>{const saved=localStorage.getItem("movilidad_route_code");if(saved)void openRoute(saved);else setReady(true);},[]);
  const counts=useMemo(()=>route?.stops.reduce((acc,item)=>({...acc,[item.status]:acc[item.status]+1}),{pendiente:0,buscada:0,en_destino:0,regresada:0})??{pendiente:0,buscada:0,en_destino:0,regresada:0},[route]);
  async function submit(event:FormEvent){event.preventDefault();if(!route||!active)return;setBusy(true);setMessage("");try{if(active.status==="pendiente"&&dni.replace(/\D/g,"")!==active.dni.replace(/\D/g,""))throw new Error("El DNI no coincide. Verificá a la persona antes de continuar.");if(!navigator.geolocation)throw new Error("Este teléfono no permite compartir ubicación.");setMessage("Tomando ubicación…");const position=await getPosition(),next:Status=active.status==="pendiente"?"buscada":active.status==="buscada"?"en_destino":active.status==="en_destino"?"regresada":"regresada",now=new Date().toISOString();const stops=route.stops.map(stop=>stop.transfer_id===active.transfer_id?{...stop,status:next,status_updated_at:now,last_latitude:position.coords.latitude,last_longitude:position.coords.longitude}:stop);const result=await supabase.from("mobility_driver_routes").update({stops,updated_at:now}).eq("id",route.id);if(result.error)throw result.error;setRoute({...route,stops});if(navigator.vibrate)navigator.vibrate([70,35,100]);setMessage("✓ Registro guardado");setDni("");window.setTimeout(()=>{setActive(null);setMessage("");},800);}catch(cause){setMessage(cause instanceof Error?cause.message:"No se pudo guardar. Probá nuevamente.");}finally{setBusy(false);}}
  if(!ready)return <main className="mobility-shell"><div className="mobility-loading">Preparando operativo…</div></main>;
  if(!route)return <main className="mobility-shell"><section className="mobility-empty"><b>OPERATIVO DE MOVILIDAD</b><h1>Ingresá tu código</h1><p>Tu movilizador te dará un código único para ver los traslados de tu vehículo.</p><form onSubmit={event=>{event.preventDefault();void openRoute(code);}}><input value={code} onChange={event=>setCode(event.target.value.toUpperCase())} placeholder="Ej.: MOV-AB12CD34" autoCapitalize="characters"/><button className="mobility-action pendiente" disabled={busy}>{busy?"ABRIENDO…":"VER MIS TRASLADOS"}</button></form>{message&&<p className="mobility-message">{message}</p>}</section></main>;
  if(active)return <main className="mobility-shell"><header className="mobility-top"><button onClick={()=>{setActive(null);setDni("");setMessage("");}}>← Volver</button><span>TRASLADO EN CURSO</span></header><section className="mobility-detail"><span className={`mobility-status ${active.status}`}>{statusCopy[active.status]}</span><h1>{active.full_name}</h1><p className="mobility-address">⌖ {active.pickup_address}</p>{active.voter_phone&&<a className="mobility-call" href={`tel:${active.voter_phone}`}>Llamar · {active.voter_phone}</a>}<div className="mobility-destination"><small>DESTINO ELECTORAL</small><b>{active.destination_name}</b><span>{active.destination_address||"Dirección a confirmar"}</span></div><form onSubmit={submit}>{active.status==="pendiente"&&<label className="mobility-dni">Confirmá el DNI completo<input value={dni} onChange={event=>setDni(event.target.value.replace(/\D/g,""))} inputMode="numeric" autoFocus placeholder="Escribí el DNI" maxLength={10}/></label>}<p className="mobility-location">⌖ Al confirmar se registrará tu ubicación.</p>{message&&<p className={message.startsWith("✓")?"mobility-success":"mobility-message"}>{message}</p>}<button className={`mobility-action ${active.status}`} disabled={busy||active.status==="regresada"}>{busy?"REGISTRANDO…":nextCopy[active.status]}</button></form></section></main>;
  const ordered=[...route.stops].sort((a,b)=>["pendiente","buscada","en_destino","regresada"].indexOf(a.status)-["pendiente","buscada","en_destino","regresada"].indexOf(b.status));
  return <main className="mobility-shell"><header className="mobility-hero"><div><span>OPERATIVO ELECTORAL · {route.operation_date}</span><h1>Mi movilidad</h1><p>{route.driver_name} · {route.vehicle_plate}</p></div><button onClick={()=>{localStorage.removeItem("movilidad_route_code");setRoute(null);setCode("");}}>Cambiar código</button></header><section className="mobility-summary"><b>{route.stops.length}</b><span>traslados asignados</span><i>{counts.pendiente} pendientes</i></section><main className="mobility-list">{ordered.map(item=><button className={`mobility-card ${item.status}`} key={item.transfer_id} onClick={()=>setActive(item)}><span className={`mobility-status ${item.status}`}>{statusCopy[item.status]}</span><strong>{item.full_name}</strong><small>{item.pickup_address}</small><em>{item.destination_name}</em><i>→</i></button>)}</main></main>;
}
