create table if not exists public.projects (
 id bigint generated by default as identity primary key,
 organization_id uuid not null references public.organizations(id) on delete cascade,
 name text not null, objective text not null,
 status text not null default 'planificado' check(status in('planificado','en_proceso','pausado','completado','cancelado')),
 priority text not null default 'media' check(priority in('baja','media','alta')),
 responsible_user_id uuid references public.profiles(id) on delete set null,
 team_id uuid references public.teams(id) on delete set null,
 source_claim_id bigint references public.claims(id) on delete set null,
 start_date date, due_date date,
 estimated_budget numeric(14,2) not null default 0 check(estimated_budget>=0),
 created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists projects_org_status_idx on public.projects(organization_id,status,due_date);
alter table public.projects enable row level security;
create policy projects_select on public.projects for select to authenticated using((select private.is_org_member(organization_id)));
create policy projects_insert on public.projects for insert to authenticated with check(created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
create policy projects_update on public.projects for update to authenticated using((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[]))) with check((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
revoke all on public.projects from anon,authenticated;
grant select,insert,update on public.projects to authenticated;
grant usage,select on sequence public.projects_id_seq to authenticated;
