alter table public.memberships add column if not exists allowed_modules text[];
create or replace function private.can_access_module(target_organization_id uuid,module_name text)
returns boolean language sql stable security definer set search_path='' as $$
select (select private.is_platform_admin()) or exists(
 select 1 from public.memberships m join public.profiles p on p.id=m.user_id
 where m.organization_id=target_organization_id and m.user_id=(select auth.uid()) and m.active and p.active
 and (m.role='admin' or (m.allowed_modules is not null and module_name=any(m.allowed_modules))
 or (m.allowed_modules is null and module_name=any(case m.role
 when 'coordinacion' then array['inicio','votantes','sedes','presupuesto','gestion','agenda','propuestas','territorio']
 when 'territorio' then array['inicio','sedes','gestion','agenda','propuestas','territorio']
 when 'finanzas' then array['inicio','presupuesto','agenda'] else array['inicio','agenda'] end)))
); $$;
revoke execute on function private.can_access_module(uuid,text) from public,anon;
grant execute on function private.can_access_module(uuid,text) to authenticated;
create table if not exists public.territorial_referents(
 id bigint generated by default as identity primary key, organization_id uuid not null references public.organizations(id) on delete cascade,
 full_name text not null,phone text,email text,referent_type text not null default 'colaborador',neighborhood text,circuit text,zone text,
 headquarters_id bigint references public.headquarters(id) on delete set null,team_id uuid references public.teams(id) on delete set null,
 reports_to_user_id uuid references public.profiles(id) on delete set null,influence_level text not null default 'medio' check(influence_level in('bajo','medio','alto')),
 status text not null default 'activo' check(status in('activo','pausado','desvinculado')),notes text,created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create index if not exists territorial_referents_org_idx on public.territorial_referents(organization_id,status,neighborhood);
alter table public.territorial_referents enable row level security;
create policy referents_select on public.territorial_referents for select to authenticated using((select private.can_access_module(organization_id,'territorio')));
create policy referents_insert on public.territorial_referents for insert to authenticated with check(created_by=(select auth.uid()) and (select private.can_access_module(organization_id,'territorio')));
create policy referents_update on public.territorial_referents for update to authenticated using((select private.can_access_module(organization_id,'territorio'))) with check((select private.can_access_module(organization_id,'territorio')));
revoke all on public.territorial_referents from anon,authenticated;
grant select,insert,update on public.territorial_referents to authenticated;
grant usage,select on sequence public.territorial_referents_id_seq to authenticated;
create policy voters_module_gate on public.voters as restrictive for all to authenticated using((select private.can_access_module(organization_id,'votantes'))) with check((select private.can_access_module(organization_id,'votantes')));
create policy headquarters_module_gate on public.headquarters as restrictive for all to authenticated using((select private.can_access_module(organization_id,'sedes'))) with check((select private.can_access_module(organization_id,'sedes')));
create policy budget_module_gate on public.budget_entries as restrictive for all to authenticated using((select private.can_access_module(organization_id,'presupuesto'))) with check((select private.can_access_module(organization_id,'presupuesto')));
create policy claims_module_gate on public.claims as restrictive for all to authenticated using((select private.can_access_module(organization_id,'gestion'))) with check((select private.can_access_module(organization_id,'gestion')));
create policy projects_module_gate on public.projects as restrictive for all to authenticated using((select private.can_access_module(organization_id,'gestion'))) with check((select private.can_access_module(organization_id,'gestion')));
create policy proposals_module_gate on public.proposals as restrictive for all to authenticated using((select private.can_access_module(organization_id,'propuestas'))) with check((select private.can_access_module(organization_id,'propuestas')));
create policy activities_module_gate on public.activities as restrictive for all to authenticated using((select private.can_access_module(organization_id,'agenda'))) with check((select private.can_access_module(organization_id,'agenda')));
