create table if not exists public.claims (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title text not null, description text not null, neighbor_name text, neighbor_phone text,
  address text not null, neighborhood text, category text not null default 'Otro',
  priority text not null default 'media' check (priority in ('baja','media','alta','urgente')),
  status text not null default 'nuevo' check (status in ('nuevo','en_revision','asignado','en_proceso','resuelto','cerrado')),
  headquarters_id bigint references public.headquarters(id) on delete set null,
  team_id uuid references public.teams(id) on delete set null,
  responsible_user_id uuid references public.profiles(id) on delete set null,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists claims_org_status_idx on public.claims(organization_id,status,created_at desc);
alter table public.claims enable row level security;
create policy claims_select on public.claims for select to authenticated using ((select private.is_org_member(organization_id)));
create policy claims_insert on public.claims for insert to authenticated with check (created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
create policy claims_update on public.claims for update to authenticated using ((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[]))) with check ((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
revoke all on public.claims from anon,authenticated;
grant select,insert,update on public.claims to authenticated;
grant usage,select on sequence public.claims_id_seq to authenticated;
