create table if not exists public.activities (
 id bigint generated by default as identity primary key,
 organization_id uuid not null references public.organizations(id) on delete cascade,
 title text not null, activity_type text not null default 'reunion', description text,
 starts_at timestamptz not null, ends_at timestamptz, location text,
 headquarters_id bigint references public.headquarters(id) on delete set null,
 team_id uuid references public.teams(id) on delete set null,
 responsible_user_id uuid references public.profiles(id) on delete set null,
 status text not null default 'programada' check(status in('programada','confirmada','realizada','cancelada')),
 created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 check(ends_at is null or ends_at>=starts_at)
);
create index if not exists activities_org_start_idx on public.activities(organization_id,starts_at);
alter table public.activities enable row level security;
create policy activities_select on public.activities for select to authenticated using((select private.is_org_member(organization_id)));
create policy activities_insert on public.activities for insert to authenticated with check(created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
create policy activities_update on public.activities for update to authenticated using((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[]))) with check((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
revoke all on public.activities from anon,authenticated;
grant select,insert,update on public.activities to authenticated;
grant usage,select on sequence public.activities_id_seq to authenticated;
