create table if not exists public.proposals (
 id bigint generated by default as identity primary key,
 organization_id uuid not null references public.organizations(id) on delete cascade,
 title text not null, theme text not null, diagnosis text not null, solution text not null,
 beneficiaries text, status text not null default 'borrador' check(status in('borrador','en_revision','aprobada','publicada','archivada')),
 responsible_user_id uuid references public.profiles(id) on delete set null,
 source_claim_id bigint references public.claims(id) on delete set null,
 project_id bigint references public.projects(id) on delete set null,
 created_by uuid not null references public.profiles(id),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists proposals_org_status_idx on public.proposals(organization_id,status,created_at desc);
alter table public.proposals enable row level security;
create policy proposals_select on public.proposals for select to authenticated using((select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
create policy proposals_insert on public.proposals for insert to authenticated with check(created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion','territorio']::public.app_role[])));
create policy proposals_update on public.proposals for update to authenticated using((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[]))) with check((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])));
revoke all on public.proposals from anon,authenticated;
grant select,insert,update on public.proposals to authenticated;
grant usage,select on sequence public.proposals_id_seq to authenticated;
