-- Ampliación operativa: trazabilidad, archivos, padrón, licencias y métricas.
alter table public.organizations
  add column if not exists logo_url text,
  add column if not exists plan_name text not null default 'base',
  add column if not exists license_status text not null default 'active'
    check (license_status in ('trial','active','suspended','expired')),
  add column if not exists license_expires_at timestamptz;

alter table public.claims
  add column if not exists latitude numeric(10,7),
  add column if not exists longitude numeric(10,7),
  add column if not exists resolved_at timestamptz;

alter table public.activities
  add column if not exists reminder_minutes integer not null default 60
    check (reminder_minutes between 0 and 10080);

alter table public.audit_log
  add column if not exists organization_id uuid references public.organizations(id) on delete cascade;

create index if not exists audit_log_org_created_idx
  on public.audit_log(organization_id, created_at desc);

create table if not exists public.entity_attachments (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  entity_type text not null check (entity_type in ('claim','project','budget','activity','proposal')),
  entity_id bigint not null,
  file_name text not null,
  storage_path text not null,
  content_type text,
  size_bytes bigint check (size_bytes is null or size_bytes between 0 and 10485760),
  uploaded_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.voter_imports (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  file_name text not null,
  file_size bigint,
  source_format text not null check (source_format in ('csv','xlsx','other')),
  status text not null default 'analisis'
    check (status in ('analisis','mapeo','listo','procesando','completado','con_errores','cancelado')),
  detected_columns jsonb not null default '[]'::jsonb,
  column_mapping jsonb not null default '{}'::jsonb,
  total_rows bigint not null default 0,
  processed_rows bigint not null default 0,
  error_rows bigint not null default 0,
  notes text,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists voter_imports_org_created_idx
  on public.voter_imports(organization_id, created_at desc);
create index if not exists voters_org_polling_idx
  on public.voters(organization_id, polling_place);

create table if not exists public.operational_targets (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  metric text not null check (metric in ('reclamos_resueltos','actividades','barrios_cubiertos','referentes_activos','proyectos_completados')),
  period_start date not null,
  period_end date not null,
  target_value numeric(14,2) not null check (target_value >= 0),
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now(),
  unique(organization_id, metric, period_start, period_end),
  check(period_end >= period_start)
);

alter table public.entity_attachments enable row level security;
alter table public.voter_imports enable row level security;
alter table public.operational_targets enable row level security;

create policy entity_attachments_select on public.entity_attachments for select to authenticated
  using ((select private.is_org_member(organization_id)));
create policy entity_attachments_insert on public.entity_attachments for insert to authenticated
  with check (uploaded_by=(select auth.uid()) and (select private.is_org_member(organization_id)));
create policy entity_attachments_delete on public.entity_attachments for delete to authenticated
  using ((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])));

create policy voter_imports_select on public.voter_imports for select to authenticated
  using ((select private.can_access_module(organization_id,'votantes')));
create policy voter_imports_insert on public.voter_imports for insert to authenticated
  with check (created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])));
create policy voter_imports_update on public.voter_imports for update to authenticated
  using ((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])))
  with check ((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])));

create policy targets_select on public.operational_targets for select to authenticated
  using ((select private.is_org_member(organization_id)));
create policy targets_write on public.operational_targets for all to authenticated
  using ((select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])))
  with check (created_by=(select auth.uid()) and (select private.has_org_role(organization_id,array['admin','coordinacion']::public.app_role[])));

drop policy if exists audit_select on public.audit_log;
create policy audit_select on public.audit_log for select to authenticated
  using (organization_id is not null and (select private.has_org_role(organization_id,array['admin']::public.app_role[])));

revoke all on public.entity_attachments, public.voter_imports, public.operational_targets from anon, authenticated;
grant select,insert,delete on public.entity_attachments to authenticated;
grant select,insert,update on public.voter_imports to authenticated;
grant select,insert,update,delete on public.operational_targets to authenticated;
grant usage,select on sequence public.entity_attachments_id_seq, public.operational_targets_id_seq to authenticated;

create or replace function private.audit_operational_change()
returns trigger language plpgsql security definer set search_path='' as $$
declare payload jsonb; row_id text; org_id uuid;
begin
  payload := case when tg_op='DELETE' then to_jsonb(old) else to_jsonb(new) end;
  row_id := coalesce(payload->>'id',payload->>'user_id',payload->>'name','unknown');
  org_id := coalesce(nullif(payload->>'organization_id','')::uuid,
                     case when tg_table_name='organizations' then nullif(payload->>'id','')::uuid else null end);
  insert into public.audit_log(actor_id,organization_id,entity_type,entity_id,action,details)
  values ((select auth.uid()),org_id,tg_table_name,row_id,lower(tg_op),
    jsonb_build_object('before',case when tg_op in ('UPDATE','DELETE') then to_jsonb(old) else null end,
                       'after',case when tg_op in ('INSERT','UPDATE') then to_jsonb(new) else null end));
  return coalesce(new,old);
end $$;
revoke execute on function private.audit_operational_change() from public,anon,authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array['claims','projects','proposals','activities','territorial_referents','headquarters','memberships','teams','organizations']
  loop
    execute format('drop trigger if exists audit_operational on public.%I',table_name);
    execute format('create trigger audit_operational after insert or update or delete on public.%I for each row execute function private.audit_operational_change()',table_name);
  end loop;
end $$;

drop trigger if exists voter_imports_touch_updated_at on public.voter_imports;
create trigger voter_imports_touch_updated_at before update on public.voter_imports
for each row execute function private.touch_updated_at();

-- Bucket privado: la aplicación guarda rutas por organización y nunca publica archivos.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values ('operational-files','operational-files',false,10485760,array['image/jpeg','image/png','image/webp','application/pdf'])
on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;

create policy operational_files_select on storage.objects for select to authenticated
using (
  bucket_id='operational-files'
  and (select private.is_org_member(((storage.foldername(name))[1])::uuid))
);
create policy operational_files_insert on storage.objects for insert to authenticated
with check (
  bucket_id='operational-files'
  and (select private.is_org_member(((storage.foldername(name))[1])::uuid))
);
create policy operational_files_delete on storage.objects for delete to authenticated
using (
  bucket_id='operational-files'
  and (select private.has_org_role(((storage.foldername(name))[1])::uuid,array['admin','coordinacion']::public.app_role[]))
);
